name: 'Alarms notifcations dev'

on:
  push:
    branches:
      - 'dev'

  # Workflow needs to be started manually
  workflow_dispatch:
    inputs:
      action_type:
        description: 'Config generator runtime env:'
        required: true
        default: 'Github-Workflow'
        type: choice
        options:
          - Action1
          - Action2
          - Action3
          - Variable-add-update
      var_key:
        description: 'Key:'
        required: true
        type: string
        default: 'None'
      var_value:
        description: 'Value:'
        required: true
        type: string
        default: 'None'

env:
  TW_ACCOUNT_SID: ${{ secrets.TW_ACCOUNT_SID }}
  TW_AUTH_TOKEN: ${{ secrets.TW_AUTH_TOKEN }}
  TW_SERVICE_SID: 'ZS66a86c95d72784c0839cc8bdb2e24d6c'
  TW_ENV_SID: 'ZE0568be8824050905a06747614a151c83'
  PY_CODE_PATH: 'source'
  JS_CODE_PATH: 'source/alarm_func.js'
  TW_URL: 'https://serverless.twilio.com/v1/Services'
  TW_CODE_URL: 'https://serverless-upload.twilio.com/v1/Services'

jobs:
  # Below job was added after the function app was created
  code_deploy:
    name: 'Twilio code upload'
    # if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5

      - name: 'Python: Install'
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'

      - name: 'Python: Install dependencies'
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ${{ env.PY_CODE_PATH }}/requirements.txt

      - name: 'Python: Deploy code to Twilio'
        run: |
          python ${{ env.PY_CODE_PATH }}/twilio_app.py ${{ env.TW_URL }} ${{ secrets.TW_ACCOUNT_SID }} ${{ secrets.TW_AUTH_TOKEN }}

      - name: 'Twilio: Add environment variables'
        if: >
          ${{
            always() && github.event_name == 'workflow_dispatch' &&
            github.event.inputs.var_key != '' && github.event.inputs.var_key != 'None'
          }}
        run: |
          python ${{ env.PY_CODE_PATH }}/twilio_env_var.py \
                 ${{ env.TW_URL }} \
                 ${{ secrets.TW_ACCOUNT_SID }} \
                 ${{ secrets.TW_AUTH_TOKEN }} \
                 ${{ env.TW_SERVICE_SID }} \
                 ${{ env.TW_ENV_SID }} \
                 ${{ github.event.inputs.var_key }} \
                 ${{ github.event.inputs.var_value }}

  # tw_function_actions:
  #   name: 'Twilio action'
  #   # always() - this job will run no matter what was the status of the dependency job
  #   if: >
  #     ${{
  #       always() && github.event_name == 'workflow_dispatch' &&
  #       github.event.inputs.var_key != '' && github.event.inputs.var_key != 'None'
  #     }}
  #   needs: [code_deploy]
  #   runs-on: self-hosted
  #   # runs-on: ubuntu-latest
  #   steps:
  #     - name: 'Twilio: Add environment variables'
  #       run: >
  #         python ${{ env.PY_CODE_PATH }}/twilio_env_var.py
  #                ${{ env.TW_URL }} \
  #                ${{ secrets.TW_ACCOUNT_SID }}
  #                ${{ secrets.TW_AUTH_TOKEN }}
  #                ${{ env.TW_SERVICE_SID }}
  #                ${{ env.TW_ENV_SID }}
  #                ${{ github.event.inputs.var_key }}
  #                ${{ github.event.inputs.var_value }}


